name: Segway Boston
favicon: null
layout_spectrum: 0.51511
typography_spectrum: 0.49417
title: 'Segway Tours '
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: UA-56697635-1
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#3C493F'
    - '#7E8D85'
    - '#B3BFB8'
    - '#F0F7F4'
    - '#A2E3C4'
  brandStrength: 0.9500684191007167
  lightness: 0.7756756632588804
  saturation: 0.506426831940189
  rhythmicContrast: 0.03722040308639407
purpose: []
